#ifndef SQURE_STRUCT_INCLUDED
#define SQURE_STRUCT_INCLUDED

//OCCUPIED_SAME_COLOR is value if square not on board
enum occupation { OCCUPIED_SAME_COLOR, OCCUPIED_DIFFERENT_COLOR, EMPTY_SQUARE };

enum pieceType {PAWN, KNIGHT, BISHOP, ROOK, QUEEN, KING};

enum pieceId { 
    WHITE_A_PAWN, WHITE_B_PAWN, WHITE_C_PAWN, WHITE_D_PAWN, WHITE_E_PAWN, WHITE_F_PAWN, WHITE_G_PAWN, WHITE_H_PAWN, 
    BLACK_A_PAWN, BLACK_B_PAWN, BLACK_C_PAWN, BLACK_D_PAWN, BLACK_E_PAWN, BLACK_F_PAWN, BLACK_G_PAWN, BLACK_H_PAWN, 
    WHITE_A_ROOK, WHITE_H_ROOK, BLACK_A_ROOK, BLACK_H_ROOK, 
    WHITE_B_KNIGHT, WHITE_G_KNIGHT, BLACK_B_KNIGHT, BLACK_G_KNIGHT, 
    WHITE_C_BISHOP, WHITE_F_BISHOP, BLACK_C_BISHOP, BLACK_F_BISHOP, 
    WHITE_QUEEN, BLACK_QUEEN, WHITE_KING, BLACK_KING
    };
struct square
{
    int x;
    int y;
};
#endif